fastlane_version "2.8.0"

default_platform :ios

platform :ios do

  before_all do
    # ensure_git_status_clean
  end

  desc "Run tests"
  lane :test do
    scan(
    	scheme: "TUM Campus App",
    	device: "iPhone 6 (10.2)",
	)
  end

end
