devices([
  "iPhone 5",
  "iPhone 6 Plus",
#  "iPad Pro (12.9 inch)",
#  "iPad Pro (9.7 inch)",
])

languages([
  "de-DE",
  # "en-US",
])

# project "TUM Campus App.xcodeproj"
scheme "Screenshots"
configuration "Debug"

output_directory "fastlane/screenshots"
derived_data_path "fastlane/DerivedData"
clear_previous_screenshots true
stop_after_first_error true
