devices([
	"iPhone 5",
  	"iPhone 8 Plus",
])

ios_version '11.0.1'

languages([
  "de-DE",
  # "en-US",
])

# project "TUM Campus App.xcodeproj"
scheme "Screenshots"
configuration "Debug"

output_directory "fastlane/screenshots"
derived_data_path "fastlane/DerivedData"
clear_previous_screenshots true
stop_after_first_error true
